export const searchOptions = ["Title", "Genre", "Tag"];
export const genres = [ // Data taken from the movielens' README 
	"Action",
	"Adventure",
	"Animation",
	"Children",
	"Comedy",
	"Crime",
	"Documentary",
	"Drama",
	"Fantasy",
	"Film-Noir",
	"Horror",
	"Musical",
	"Mystery",
	"Romance",
	"Sci-Fi",
	"Thriller",
	"War",
	"Western",
];
